variables:
  - template: templates/variables.yml

trigger: none

stages:
  - stage:
    displayName: 'Migration ci pipeline'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            clean: true
            submodules: true
            lfs: true
            
          - task: UseDotNet@2
            displayName: 'Use .NET SDK'
            inputs:
              useGlobalJson: true
          
          - bash: |
              dotnet restore $(SolutionPath)
            displayName: 'Dotnet Restore'
            
          - bash: |
              dotnet build $(SolutionPath) --configuration Release --no-restore
            displayName: 'Dotnet Build'

          - bash: |
              dotnet test $(SolutionPath) --configuration Release --no-build --no-restore
            displayName: 'Dotnet Test'

          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFiles: '**/TestResults/*.trx'
              testResultsFormat: 'VSTest'
              failTaskOnFailedTests: true
            condition: succeededOrFailed()